# Generated by Django 2.2 on 2020-01-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcr_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='ranking_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='summary',
            name='sentiment_score',
            field=models.FloatField(default=0),
        ),
    ]
