# Generated by Django 2.2 on 2020-01-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcr_home', '0003_auto_20200117_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_review_count',
            field=models.IntegerField(default=0),
        ),
    ]
